### ISSUE TITLE
Could not load file or assembly 'TaskBuilder.fs

### ISSUE THREAD

**Issue by vmenge** [Zaid-Ajaj/Giraffe.GoodRead#4]
## Description

Upon adding GoodRead to a relatively fresh Giraffe project, when using it I get a `Could not load file or assembly 'TaskBuilder.fs` message on whichever endpoint is using it.

```
let registerUser (conf: AuthConfig)=
        task {
            return json {| Test = $"{conf.DbConfig.Database}!!" |}
        }


let routes : HttpFunc -> HttpContext -> HttpFuncResult =
        subRoute
            "/auth"
            (choose [ GET
                      >=> choose [ route "/" >=> Require.services (registerUser)
                                   route "/ble" >=> basic2 ] ])
```

After adding TaskBuilder NuGet package, now I get:

`Could not load file or assembly 'Giraffe, Version=3.4.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)`

## Error messages, screenshots

Initial Error:
```
 An unhandled exception has occurred while executing the request.
      System.IO.FileNotFoundException: Could not load file or assembly 'TaskBuilder.fs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

      File name: 'TaskBuilder.fs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
         at Giraffe.GoodRead.Extensions.contextTask(FSharpFunc`2 contextMap, FSharpFunc`2 next, HttpContext ctx)
         at <StartupCode$Giraffe-GoodRead>.$Require.apply@24-3.Invoke(FSharpFunc`2 next, HttpContext ctx)
         at Authentication.Module.Api.Auth.Controller.routes@20.Invoke(FSharpFunc`2 next, HttpContext ctx) in /app/src/Authentication/Authentication.Module/Api.Auth.Controller.fs:line 20
         at Giraffe.Core.chooseHttpFunc@122.Invoke(Unit unitVar)
         at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
         at Giraffe.Core.chooseHttpFunc@122.Invoke(Unit unitVar)
         at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
         at Giraffe.SubRouting.routeWithPartialPath@24.Invoke(Unit unitVar)
         at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
         at Giraffe.Core.chooseHttpFunc@122.Invoke(Unit unitVar)
         at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
         at Giraffe.Middleware.Invoke@31.Invoke(Unit unitVar)
         at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
         at Giraffe.Middleware.Invoke@64-5.Invoke(Unit unitVar)
         at Ply.TplPrimitives.tryWith[u](FSharpFunc`2 continuation, FSharpFunc`2 catch)
```

Error after adding TaskBuilder.fs 
```
 An unhandled exception has occurred while executing the request.
      System.IO.FileLoadException: Could not load file or assembly 'Giraffe, Version=3.4.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
      File name: 'Giraffe, Version=3.4.0.0, Culture=neutral, PublicKeyToken=null'
         at Giraffe.GoodRead.RequireImpl.getService[t](HttpContext context)
         at Giraffe.GoodRead.RequireImpl.service@17.Invoke(HttpContext httpContext)
         at Giraffe.GoodRead.Reader.bindM@14.Invoke(b environment)
         at Giraffe.GoodRead.Extensions.contextTask@23.Invoke(Unit unitVar)
         at FSharp.Control.Tasks.TaskBuilder.run[a](FSharpFunc`2 firstStep)
      --- End of stack trace from previous location ---
         at Giraffe.Core.chooseHttpFunc@122.Invoke(Unit unitVar)
         at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
         at Giraffe.Core.chooseHttpFunc@122.Invoke(Unit unitVar)
         at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
         at Giraffe.SubRouting.routeWithPartialPath@24.Invoke(Unit unitVar)
         at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
         at Giraffe.Core.chooseHttpFunc@122.Invoke(Unit unitVar)
         at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
         at Giraffe.Middleware.Invoke@31.Invoke(Unit unitVar)
         at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
         at Giraffe.Middleware.Invoke@64-5.Invoke(Unit unitVar)
         at Ply.TplPrimitives.tryWith[u](FSharpFunc`2 continuation, FSharpFunc`2 catch)
````

## Other information

* Operating System:
    - Host: Windows 10 Pro 20H2
    - Guest (Docker): Ubuntu Focal
    - Docker Image: `mcr.microsoft.com/dotnet/sdk:5.0-focal-amd64`
* Platform
    - [ x ] dotnet 5

**Comment by Dzoukr** [comment]
Hi, just got into the same issue. Fixing `Giraffe` to `v4.1` works, but I think this is based on Giraffe 4 uses `TaskBuilder.fs` and the 5th version has now `Ply` for task CE.

**Comment by Zaid-Ajaj** [comment]
I will updating this library soon to latest Giraffe v5, just a bit low on time/capacity these days :/

**Comment by Zaid-Ajaj** [comment]
Published Giraffe.GoodRead v2.0 which now depends on latest Giraffe v5.0 and net5.0
